// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHrNwc6hbCdQBQCpKGf9SjES0gnX3hV3s',
    appId: '1:454171307433:web:8a1612c204b00ab61568b8',
    messagingSenderId: '454171307433',
    projectId: 'community-62b1e',
    authDomain: 'community-62b1e.firebaseapp.com',
    storageBucket: 'community-62b1e.firebasestorage.app',
    measurementId: 'G-KE26QKLFR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQClVdDIk3WbnE1XnEGULNzK9PitNs3-w',
    appId: '1:454171307433:android:4507e6fc233940f41568b8',
    messagingSenderId: '454171307433',
    projectId: 'community-62b1e',
    storageBucket: 'community-62b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCgCLMy7Wt4krJsfjk49Vf7XdwHnmY5s',
    appId: '1:454171307433:ios:a701d19d8c42a1401568b8',
    messagingSenderId: '454171307433',
    projectId: 'community-62b1e',
    storageBucket: 'community-62b1e.firebasestorage.app',
    iosBundleId: 'com.example.community',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCgCLMy7Wt4krJsfjk49Vf7XdwHnmY5s',
    appId: '1:454171307433:ios:a701d19d8c42a1401568b8',
    messagingSenderId: '454171307433',
    projectId: 'community-62b1e',
    storageBucket: 'community-62b1e.firebasestorage.app',
    iosBundleId: 'com.example.community',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHrNwc6hbCdQBQCpKGf9SjES0gnX3hV3s',
    appId: '1:454171307433:web:d49063509ea34bc11568b8',
    messagingSenderId: '454171307433',
    projectId: 'community-62b1e',
    authDomain: 'community-62b1e.firebaseapp.com',
    storageBucket: 'community-62b1e.firebasestorage.app',
    measurementId: 'G-N8E6NC1DK8',
  );
}
